CREATE TABLE MEMBER (
MEMBERID VARCHAR(30) PRIMARY KEY,
MEMBERPW VARCHAR(30) NOT NULL,
MEMBERNAME VARCHAR(10) NOT NULL,
PHONENUMBER VARCHAR(11) NOT NULL,
ZIPCODE INT,
ADDRESS VARCHAR(50),
ADDRESSDETAIL VARCHAR(50),
EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORY (
CATEGORYNUM INT PRIMARY KEY AUTO_INCREMENT,
CATEGORYNAME VARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORYDETAIL (
CATEGORYDETAILNUM INT PRIMARY KEY AUTO_INCREMENT,
CATEGORYDETAILNAME VARCHAR(50) NOT NULL,
CATEGORYNUM INT NOT NULL,
FOREIGN KEY(CATEGORYNUM) REFERENCES CATEGORY(CATEGORYNUM)
);

CREATE TABLE PRODUCT (
PRODUCTNUM INT PRIMARY KEY AUTO_INCREMENT, 
PRODUCTNAME VARCHAR(200) NOT NULL,
COMPANY VARCHAR(30) NOT NULL,
PRODUCTPRICE INT NOT NULL,
PRODUCTEXPLAIN VARCHAR(200),
CATEGORYNUM INT NOT NULL,
CATEGORYDETAILNUM INT NOT NULL,
FOREIGN KEY(CATEGORYNUM) REFERENCES CATEGORY(CATEGORYNUM),
FOREIGN KEY(CATEGORYDETAILNUM) REFERENCES CATEGORYDETAIL(CATEGORYDETAILNUM)
);

CREATE TABLE CART (
CARTNUM INT PRIMARY KEY AUTO_INCREMENT,
CARTTIME TIMESTAMP DEFAULT NOW(),
CARTCOUNT INT,
PRODUCTNUM INT NOT NULL,
MEMBERID VARCHAR(30) NOT NULL,
FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCT(PRODUCTNUM),
FOREIGN KEY(MEMBERID) REFERENCES MEMBER(MEMBERID)
);

CREATE TABLE WISHLIST (
WISHLISTNUM INT PRIMARY KEY AUTO_INCREMENT,
WISHLISTTIME TIMESTAMP DEFAULT NOW(),
MEMBERID VARCHAR(30) NOT NULL,
PRODUCTNUM INT NOT NULL,
UNIQUE(PRODUCTNUM,MEMBERID),
FOREIGN KEY(MEMBERID) REFERENCES MEMBER(MEMBERID),
FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCT(PRODUCTNUM)
);

CREATE TABLE IMAGES (
IMAGENUM INT PRIMARY KEY AUTO_INCREMENT,
PATH VARCHAR(1000) NOT NULL,
PRODUCTNUM INT NOT NULL,
FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCT(PRODUCTNUM)
);

CREATE TABLE PAY (
PAYNUM INT PRIMARY KEY AUTO_INCREMENT,
PAYTIME TIMESTAMP DEFAULT NOW(),
PAYMETHOD VARCHAR(50) NOT NULL,
MEMBERID VARCHAR(30) NOT NULL,
FOREIGN KEY(MEMBERID) REFERENCES MEMBER(MEMBERID)
);

CREATE TABLE PAYDETAIL (
PAYDETAILNUM INT PRIMARY KEY AUTO_INCREMENT,
PAYNUM INT,
PRODUCTNUM INT,
PAYCOUNT INT NOT NULL,
FOREIGN KEY(PAYNUM) REFERENCES PAY(PAYNUM),
FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCT(PRODUCTNUM)
);
